apiVersion: v1
data:
  nginx.conf:
    events { }

    http {
      server { 
        listen 80;
        listen 443 ssl;

        ssl_certificate /etc/nginx/tls/certificado.crt;
        ssl_certificate_key /etc/nginx/tls/chave-privada.key;
        
        location / {
          return 200 'Ola terraqueos!\n';
          add_header Content-Type text/plain;
        }
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2024-02-01T17:07:39Z"
  name: nginx-config
  namespace: default
  resourceVersion: "320351"
  uid: 877c6671-e5ba-4229-9095-41161e192196
